//! Manages CLIProxyAPI as a child process within SongPlayer.
//!
//! CLIProxyAPI is a Go binary that provides an OpenAI-compatible API by
//! authenticating with Claude via OAuth. SongPlayer manages its lifecycle
//! and handles Claude OAuth login via CLIProxyAPI's native `-claude-login`
//! flow with callback URL forwarding.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::io::AsyncBufReadExt;
use tokio::process::{Child, ChildStdout, Command};
use tokio::sync::RwLock;
use tracing::{info, warn};

/// Holds a login child process and its stdout handle.
/// The stdout must be kept alive to prevent SIGPIPE from killing the process.
struct LoginProcess {
    child: Child,
    _stdout: ChildStdout,
}

/// Default port for the embedded CLIProxyAPI instance.
const DEFAULT_PROXY_PORT: u16 = 18787;

/// OAuth callback port used by CLIProxyAPI for Claude login.
const OAUTH_CALLBACK_PORT: u16 = 54545;

/// Name of the CLIProxyAPI binary (without extension).
#[cfg(windows)]
const PROXY_BINARY_NAME: &str = "CLIProxyAPI.exe";
#[cfg(not(windows))]
const PROXY_BINARY_NAME: &str = "CLIProxyAPI";

/// State of the managed CLIProxyAPI process.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyStatus {
    pub running: bool,
    pub api_url: String,
    pub authenticated: bool,
    pub pid: Option<u32>,
}

/// Manages the CLIProxyAPI child process and Claude OAuth.
pub struct ProxyManager {
    child: Arc<RwLock<Option<Child>>>,
    login_child: Arc<RwLock<Option<LoginProcess>>>,
    port: u16,
    data_dir: PathBuf,
}

impl ProxyManager {
    /// Create a new proxy manager.
    ///
    /// `data_dir` is the application data directory where config and auth
    /// files are stored. The binary is searched in `data_dir/tools/` first,
    /// then on the system PATH.
    pub fn new(data_dir: PathBuf, port: u16) -> Self {
        Self {
            child: Arc::new(RwLock::new(None)),
            login_child: Arc::new(RwLock::new(None)),
            port,
            data_dir,
        }
    }

    /// Discover the CLIProxyAPI binary path.
    #[cfg_attr(test, mutants::skip)]
    fn binary_path(&self) -> Option<PathBuf> {
        // 1. Check data_dir/tools/
        let tools_path = self.data_dir.join("tools").join(PROXY_BINARY_NAME);
        if tools_path.exists() {
            return Some(tools_path);
        }

        // 2. Check PATH
        #[cfg(windows)]
        let which_cmd = "where";
        #[cfg(not(windows))]
        let which_cmd = "which";

        if let Ok(output) = std::process::Command::new(which_cmd)
            .arg(PROXY_BINARY_NAME)
            .output()
        {
            if output.status.success() {
                let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !path.is_empty() {
                    return Some(PathBuf::from(path));
                }
            }
        }

        None
    }

    #[cfg_attr(test, mutants::skip)]
    fn auth_dir(&self) -> PathBuf {
        self.data_dir.join(".cli-proxy-api")
    }

    #[cfg_attr(test, mutants::skip)]
    fn config_path(&self) -> PathBuf {
        self.data_dir.join("cli-proxy-api-config.yaml")
    }

    /// Check if Claude credentials exist (either OAuth tokens or API key in config).
    #[cfg_attr(test, mutants::skip)]
    pub fn is_claude_authenticated(&self) -> bool {
        if let Ok(content) = std::fs::read_to_string(self.config_path()) {
            if content.contains("claude-api-key:") {
                return true;
            }
        }
        let auth_dir = self.auth_dir();
        auth_dir.exists()
            && std::fs::read_dir(&auth_dir)
                .map(|entries| {
                    entries
                        .filter_map(|e| e.ok())
                        .any(|e| e.file_name().to_string_lossy().contains("claude"))
                })
                .unwrap_or(false)
    }

    /// Write the config YAML file for CLIProxyAPI.
    #[cfg_attr(test, mutants::skip)]
    async fn write_config(&self, api_key: Option<&str>) -> anyhow::Result<()> {
        let auth_dir = self.auth_dir();

        let key_section = if let Some(key) = api_key {
            format!(
                r#"
claude-api-key:
  - api-key: "{key}"
"#
            )
        } else {
            String::new()
        };

        // Use forward slashes in YAML — backslashes are escape chars in YAML strings.
        let auth_dir_str = auth_dir.display().to_string().replace('\\', "/");
        let config_content = format!(
            r#"# Auto-generated by SongPlayer - do not edit
host: "127.0.0.1"
port: {port}
auth-dir: "{auth_dir_str}"
debug: false
logging-to-file: false
request-retry: 2
claude-oauth:
  - cloak:
      mode: "never"
{key_section}"#,
            port = self.port,
        );

        tokio::fs::create_dir_all(&auth_dir).await?;
        tokio::fs::write(self.config_path(), config_content).await?;
        Ok(())
    }

    /// Probe the configured port for a healthy CLIProxyAPI instance.
    ///
    /// Returns true iff `GET /v1/models` responds with 2xx within a short
    /// timeout. Used by `start()` to adopt an existing proxy (e.g., an
    /// orphan from a previous SongPlayer that didn't get cleaned up, or
    /// an externally-managed proxy) and by `is_running()` as a fallback
    /// when our internal child handle is empty.
    async fn probe_port(&self) -> bool {
        let url = format!("http://127.0.0.1:{}/v1/models", self.port);
        match reqwest::Client::new()
            .get(&url)
            .timeout(std::time::Duration::from_secs(2))
            .send()
            .await
        {
            Ok(resp) => resp.status().is_success(),
            Err(_) => false,
        }
    }

    /// Start the CLIProxyAPI process and wait for it to become ready.
    ///
    /// Order of operations:
    /// 1. If our own child handle is alive → return Ok.
    /// 2. If the port is already serving `/v1/models` (healthy orphan
    ///    from a previous SongPlayer or externally-managed proxy) →
    ///    adopt, return Ok without spawning.
    /// 3. Otherwise spawn a fresh child and poll readiness (10 × 1 s).
    ///
    /// Returns Err if:
    /// - No existing proxy to adopt AND binary not found
    /// - Spawn fails
    /// - Process exits immediately (config error, missing auth, or the
    ///   port got bound by something unhealthy between the probe and
    ///   the spawn — rare)
    /// - Health check (`/v1/models`) doesn't respond within ~10 seconds
    ///
    /// On any failure, the stale child handle is cleared so a subsequent
    /// `status()` correctly reports `running: false`.
    #[cfg_attr(test, mutants::skip)]
    pub async fn start(&self) -> anyhow::Result<()> {
        // 1. Already running?
        if self.is_running().await {
            return Ok(());
        }

        // 2. Is something else already serving on our port? Adopt it.
        //    This closes the orphan-CLIProxyAPI bug observed after the
        //    2026-04-22 0.20.0 deploy where a previous SongPlayer's
        //    subprocess kept port 18787 bound and the new SongPlayer's
        //    watchdog loop tried to spawn its own every 30 s — each spawn
        //    immediately exiting status 0 because the port was taken.
        if self.probe_port().await {
            info!(
                port = self.port,
                "CLIProxyAPI already running externally, adopting existing instance"
            );
            return Ok(());
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        let existing_key = self.read_existing_api_key().await;
        self.write_config(existing_key.as_deref()).await?;

        info!(binary = %binary.display(), port = self.port, "starting CLIProxyAPI");

        let mut cmd = Command::new(&binary);
        cmd.arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .kill_on_drop(true);

        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            cmd.creation_flags(0x08000000); // CREATE_NO_WINDOW
        }

        let child = cmd.spawn()?;
        {
            let mut guard = self.child.write().await;
            *guard = Some(child);
        }

        // Poll readiness: 10 attempts, 1s interval.
        // Fail fast if the child exits before we reach readiness.
        let url = format!("http://127.0.0.1:{}/v1/models", self.port);
        let http = reqwest::Client::new();

        for attempt in 1..=10u32 {
            tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;

            // Has the child already exited? If so, clear the handle and fail.
            {
                let mut guard = self.child.write().await;
                if let Some(ref mut child) = *guard {
                    if let Ok(Some(status)) = child.try_wait() {
                        *guard = None;
                        anyhow::bail!(
                            "CLIProxyAPI exited during startup (attempt {attempt}, status: {status})"
                        );
                    }
                } else {
                    // Somehow cleared — give up.
                    anyhow::bail!("CLIProxyAPI handle lost during startup");
                }
            }

            // Is it responding?
            match http
                .get(&url)
                .timeout(std::time::Duration::from_secs(2))
                .send()
                .await
            {
                Ok(resp) if resp.status().is_success() => {
                    info!(
                        port = self.port,
                        attempt, "CLIProxyAPI started successfully"
                    );
                    return Ok(());
                }
                Ok(resp) => {
                    warn!(
                        attempt,
                        status = %resp.status(),
                        "CLIProxyAPI responded with non-success, retrying"
                    );
                }
                Err(_) => {
                    // Not ready yet — keep polling.
                }
            }
        }

        // Timed out waiting for readiness — kill the process and report failure.
        {
            let mut guard = self.child.write().await;
            if let Some(mut child) = guard.take() {
                child.kill().await.ok();
                child.wait().await.ok();
            }
        }
        anyhow::bail!("CLIProxyAPI failed to respond on {url} within 10 seconds")
    }

    /// Stop the CLIProxyAPI process.
    #[cfg_attr(test, mutants::skip)]
    pub async fn stop(&self) -> anyhow::Result<()> {
        let mut guard = self.child.write().await;
        if let Some(mut child) = guard.take() {
            info!("stopping CLIProxyAPI");
            child.kill().await.ok();
            child.wait().await.ok();
        }
        Ok(())
    }

    /// Get current status.
    #[cfg_attr(test, mutants::skip)]
    pub async fn status(&self) -> ProxyStatus {
        let running = self.is_running().await;
        let pid = {
            let guard = self.child.read().await;
            guard.as_ref().and_then(|c| c.id())
        };

        ProxyStatus {
            running,
            api_url: format!("http://127.0.0.1:{}/v1", self.port),
            authenticated: self.is_claude_authenticated(),
            pid,
        }
    }

    async fn is_running(&self) -> bool {
        // Check our own child handle first — fastest and authoritative
        // for children WE spawned.
        {
            let mut guard = self.child.write().await;
            if let Some(ref mut child) = *guard {
                match child.try_wait() {
                    Ok(None) => return true,
                    _ => {
                        *guard = None;
                    }
                }
            }
        }
        // Fallback: probe the port. Catches externally-managed or orphan
        // proxies that we should treat as "already running" to avoid the
        // watchdog spawning a duplicate that can't bind the port.
        self.probe_port().await
    }

    // ── Claude Login via CLIProxyAPI ──

    /// Start the Claude OAuth login flow.
    ///
    /// Spawns `CLIProxyAPI -claude-login -no-browser` and reads the auth URL
    /// from stdout. The login process listens on port 54545 for the OAuth
    /// callback. After the user authorizes, the browser redirects to
    /// `localhost:54545/callback?code=...` which fails (since the server is
    /// remote). The user copies the full URL from the browser error page and
    /// pastes it into SongPlayer, which forwards it via `complete_login()`.
    #[cfg_attr(test, mutants::skip)]
    pub async fn claude_login(&self) -> anyhow::Result<String> {
        // Kill any previous login process
        {
            let mut guard = self.login_child.write().await;
            if let Some(mut proc) = guard.take() {
                proc.child.kill().await.ok();
                proc.child.wait().await.ok();
            }
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        let existing_key = self.read_existing_api_key().await;
        self.write_config(existing_key.as_deref()).await?;

        info!(binary = %binary.display(), "starting CLIProxyAPI claude-login");

        let mut cmd = Command::new(&binary);
        cmd.arg("-claude-login")
            .arg("-no-browser")
            .arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .kill_on_drop(true);

        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            cmd.creation_flags(0x08000000); // CREATE_NO_WINDOW
        }

        let mut child = cmd.spawn()?;

        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| anyhow::anyhow!("failed to capture login process stdout"))?;

        let mut reader = tokio::io::BufReader::new(stdout);
        let mut auth_url: Option<String> = None;
        let mut line_buf = String::new();

        let deadline = tokio::time::Instant::now() + tokio::time::Duration::from_secs(10);
        loop {
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() {
                break;
            }

            line_buf.clear();
            match tokio::time::timeout(remaining, reader.read_line(&mut line_buf)).await {
                Ok(Ok(0)) => break,
                Ok(Ok(_)) => {
                    let line = line_buf.trim_end();
                    info!(line = %line, "claude-login stdout");
                    if let Some(url_start) = line.find("https://") {
                        let url = line[url_start..].split_whitespace().next().unwrap_or("");
                        if !url.is_empty() {
                            auth_url = Some(url.to_string());
                            break;
                        }
                    }
                }
                Ok(Err(e)) => {
                    warn!(?e, "error reading claude-login stdout");
                    break;
                }
                Err(_) => break,
            }
        }

        let url = auth_url.ok_or_else(|| {
            anyhow::anyhow!("claude-login did not produce an auth URL within 10s")
        })?;

        // Keep both child AND stdout handle alive — dropping stdout closes the
        // pipe and kills the process via SIGPIPE.
        let stdout_handle = reader.into_inner();
        {
            let mut guard = self.login_child.write().await;
            *guard = Some(LoginProcess {
                child,
                _stdout: stdout_handle,
            });
        }

        info!("claude-login URL obtained, waiting for user to paste callback URL");
        Ok(url)
    }

    /// Complete the OAuth login by forwarding the callback URL to CLIProxyAPI.
    ///
    /// After the user authorizes, the browser redirects to
    /// `localhost:54545/callback?code=XXX&state=YYY`. Since the server is
    /// remote, this fails in the browser. The user copies the full URL and
    /// pastes it here. SongPlayer forwards it to CLIProxyAPI's callback
    /// endpoint on localhost.
    #[cfg_attr(test, mutants::skip)]
    pub async fn complete_login(&self, callback_url: &str) -> anyhow::Result<()> {
        let query = if let Some(pos) = callback_url.find('?') {
            &callback_url[pos..]
        } else {
            anyhow::bail!("callback URL must contain query parameters (?code=...&state=...)");
        };

        let target = format!("http://127.0.0.1:{OAUTH_CALLBACK_PORT}/callback{query}");
        info!("forwarding OAuth callback to CLIProxyAPI");

        // Don't follow redirects — CLIProxyAPI returns 302 on success
        let resp = reqwest::Client::builder()
            .redirect(reqwest::redirect::Policy::none())
            .build()?
            .get(&target)
            .timeout(std::time::Duration::from_secs(10))
            .send()
            .await?;

        let status = resp.status().as_u16();
        if status >= 400 {
            let body = resp.text().await.unwrap_or_default();
            anyhow::bail!("OAuth callback failed (HTTP {status}): {body}");
        }

        // Give CLIProxyAPI a moment to save tokens
        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;

        // Kill the login process — it's done
        {
            let mut guard = self.login_child.write().await;
            if let Some(mut proc) = guard.take() {
                proc.child.kill().await.ok();
                proc.child.wait().await.ok();
            }
        }

        // Restart the main proxy to pick up new credentials
        if self.is_running().await {
            info!("restarting CLIProxyAPI to use new credentials");
            self.stop().await?;
            self.start().await?;
        }

        info!("Claude OAuth login completed");
        Ok(())
    }

    /// Read existing API key from config file (if any).
    #[cfg_attr(test, mutants::skip)]
    async fn read_existing_api_key(&self) -> Option<String> {
        let content = tokio::fs::read_to_string(self.config_path()).await.ok()?;
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("- api-key:") || trimmed.starts_with("api-key:") {
                let value = trimmed.split(':').nth(1)?.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
        None
    }

    /// Auto-start the proxy if the binary is available.
    #[cfg_attr(test, mutants::skip)]
    pub async fn auto_start(&self) {
        if self.binary_path().is_some() {
            if let Err(e) = self.start().await {
                warn!(?e, "failed to auto-start CLIProxyAPI");
            }
        }
    }

    /// Return the default port.
    #[cfg_attr(test, mutants::skip)]
    pub fn default_port() -> u16 {
        DEFAULT_PROXY_PORT
    }
}

/// Determine the data directory for CLIProxyAPI config and auth.
#[cfg_attr(test, mutants::skip)]
pub fn default_data_dir() -> PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."))
}

#[cfg(test)]
mod tests {
    use super::*;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    /// Parse `port` from a wiremock `http://127.0.0.1:PORT` URI.
    fn mock_port(mock: &MockServer) -> u16 {
        let uri = mock.uri();
        let after_colon = uri.rsplit(':').next().expect("mock uri has port segment");
        after_colon.parse().expect("mock port parses as u16")
    }

    /// Regression for the orphan-CLIProxyAPI bug (observed after
    /// 2026-04-22 0.20.0 deploy):
    ///
    /// When a previous SongPlayer exited without killing its CLIProxyAPI
    /// subprocess, the orphan kept port 18787 bound. The new SongPlayer's
    /// `start()` didn't probe the port first — it tried to spawn a child
    /// which immediately exited with status 0 (port already in use), and
    /// the watchdog loop logged "restart failed" every 30s forever. The
    /// orphan was responding healthily to `/v1/models`; we just never
    /// asked.
    ///
    /// Fix: `start()` probes `GET /v1/models` before spawning. If an
    /// existing healthy proxy answers 200 we adopt it — no spawn, no
    /// watchdog churn, no need for the binary even to exist.
    #[tokio::test]
    async fn start_adopts_existing_healthy_proxy_without_spawning() {
        let mock = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "object": "list",
                "data": []
            })))
            .mount(&mock)
            .await;

        // data_dir points at a temp dir that does NOT contain a binary —
        // if the implementation tries to spawn, binary_path() will return
        // None and the whole start() path will fail. Adopting short-
        // circuits BEFORE binary_path() is consulted.
        let tmp = tempfile::tempdir().expect("temp dir");
        let manager = ProxyManager::new(tmp.path().to_path_buf(), mock_port(&mock));

        manager
            .start()
            .await
            .expect("start() must succeed by adopting the healthy proxy");

        // Confirm we did NOT spawn a child of our own.
        let guard = manager.child.read().await;
        assert!(
            guard.is_none(),
            "start() must not spawn a child when an existing healthy proxy is present"
        );
    }

    /// When no proxy is serving on the port, and the binary is missing,
    /// `start()` must surface a real error rather than silently adopting
    /// nothing. Guards against "probe returned false → forgot to fall
    /// through" logic errors in the implementation.
    #[tokio::test]
    async fn start_errors_when_no_existing_proxy_and_no_binary() {
        let tmp = tempfile::tempdir().expect("temp dir");
        // Pick a port that almost certainly has nothing listening. 1 is
        // privileged on Unix and the OS will refuse to connect; on
        // Windows the probe will time out → both paths produce the
        // "nothing healthy here" branch.
        let manager = ProxyManager::new(tmp.path().to_path_buf(), 1);

        let err = manager
            .start()
            .await
            .expect_err("start() must fail when no adopt target and no binary");
        let msg = err.to_string();
        assert!(
            msg.contains("binary not found")
                || msg.contains("CLIProxyAPI failed to respond")
                || msg.contains("exited during startup"),
            "unexpected error shape: {msg}"
        );
    }

    /// `is_running()` must fall back to a port probe so the watchdog
    /// doesn't churn restarts when an externally-managed healthy proxy
    /// is already serving requests. Without this fallback, a fresh
    /// SongPlayer process (internal `child` handle = None) thinks the
    /// proxy is down even when the port is alive.
    #[tokio::test]
    async fn is_running_returns_true_for_externally_managed_healthy_proxy() {
        let mock = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200))
            .mount(&mock)
            .await;

        let tmp = tempfile::tempdir().expect("temp dir");
        let manager = ProxyManager::new(tmp.path().to_path_buf(), mock_port(&mock));

        assert!(
            manager.is_running().await,
            "is_running() must return true when the port is serving /v1/models"
        );
    }

    /// When we own a live spawned child, `is_running()` must return
    /// true from the `Ok(None)` (still running) arm WITHOUT consulting
    /// the port probe. If the probe is the only thing keeping this
    /// assertion true (e.g., the `Ok(None)` arm is removed), a watchdog
    /// on a machine with no externally-bound port would think its own
    /// healthy proxy is dead and try to double-spawn.
    ///
    /// Regression guard for the cargo-mutants survivor
    /// `delete match arm Ok(None) in ProxyManager::is_running` (caught
    /// 2026-04-22 on PR #50).
    #[tokio::test]
    async fn is_running_returns_true_for_owned_live_child_even_when_probe_fails() {
        let tmp = tempfile::tempdir().expect("temp dir");
        // Port 1 is privileged and unbound on the CI runner — probe()
        // will return false. The only way is_running() can return true
        // is via the `Ok(None)` arm on our live child.
        let manager = ProxyManager::new(tmp.path().to_path_buf(), 1);

        // Spawn a long-living no-op child. We don't need a real
        // CLIProxyAPI — just something whose try_wait() returns
        // `Ok(None)` for a while.
        #[cfg(windows)]
        let mut cmd = tokio::process::Command::new("cmd");
        #[cfg(windows)]
        cmd.args(["/c", "ping -n 30 127.0.0.1 > nul"]);
        #[cfg(not(windows))]
        let mut cmd = tokio::process::Command::new("sh");
        #[cfg(not(windows))]
        cmd.args(["-c", "sleep 30"]);
        cmd.kill_on_drop(true);
        let child = cmd.spawn().expect("spawn no-op child");
        *manager.child.write().await = Some(child);

        assert!(
            manager.is_running().await,
            "is_running() must return true via Ok(None) arm when we own a live child, \
             regardless of whether the port probe would succeed"
        );

        // Cleanup: drop the child (kill_on_drop handles the actual kill).
        *manager.child.write().await = None;
    }
}
